version: "3.7"

services:
  go_api:
    image: k8s-api:1.0
    build:
      context: .
      args:
        goflags: ""
    restart: always
    ports:
      - "3000:3000"
      - "4000:4000"
    volumes:
      - ./:/src