apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-api
spec:
  selector:
    matchLabels:
      app: k8s-api
  template:
    metadata:
      labels:
        app: k8s-api
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      containers:
        - name: app
          image: k8s-api:1.0
          ports:
            - name: app
              containerPort: 3000
            - name: app-debug
              containerPort: 4000
          readinessProbe:
            httpGet:
              path: /v1/health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-api
spec:
  selector:
    service: k8s-api
  ports:
    - name: app
      port: 3000
      targetPort: app
    - name: app-debug
      port: 4000
      targetPort: app-debug
